/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufjf.lp3;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author igor
 */
public class JanelaPrincipal extends javax.swing.JFrame {

   private Connection conexao;
   private PreparedStatement opInsere;
   private PreparedStatement opExclui;

   /**
    * Creates new form JanelaPrincipal
    */
   public JanelaPrincipal() {
      try {
         Class.forName("org.apache.derby.jdbc.ClientDriver");
      } catch (ClassNotFoundException ex) {
         JOptionPane.showMessageDialog(this, "Driver não disponível", "Sem driver!", JOptionPane.ERROR_MESSAGE);
         Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
         System.exit(1);
      }

      try {
         conexao = DriverManager.getConnection("jdbc:derby://localhost:1527/2016-3-dcc", "usuario", "senha");
      } catch (SQLException ex) {
         JOptionPane.showMessageDialog(this, "Não foi possível conectar ao banco de dados!", "Sem banco!", JOptionPane.ERROR_MESSAGE);
         Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
         System.exit(2);
      }

      try {
         opInsere = conexao.prepareStatement("INSERT INTO pessoa(nome, telefone) VALUES (?, ?)");
         opExclui = conexao.prepareStatement("DELETE FROM pessoa WHERE telefone=?");
      } catch (SQLException ex) {
         JOptionPane.showMessageDialog(this, "Não foi possível preparar as operações do banco de dados!", "Erro ao preparar!", JOptionPane.ERROR_MESSAGE);
         Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
      }
      initComponents();
      setLocationRelativeTo(null);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      txtNome = new javax.swing.JTextField();
      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      txtTelefone = new javax.swing.JTextField();
      btnSalvar = new javax.swing.JButton();
      jButton1 = new javax.swing.JButton();
      jScrollPane1 = new javax.swing.JScrollPane();
      tblPessoa = new javax.swing.JTable();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("Agenda");

      jLabel1.setText("Nome");

      jLabel2.setText("Telefone");

      btnSalvar.setText("Salvar");
      btnSalvar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSalvarActionPerformed(evt);
         }
      });

      jButton1.setText("Excluir");
      jButton1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
         }
      });

      tblPessoa.setModel(new PessoaTableModel(conexao));
      jScrollPane1.setViewportView(tblPessoa);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(btnSalvar)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton1)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
         .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
         .addComponent(txtNome)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel1)
               .addComponent(jLabel2))
            .addGap(0, 0, Short.MAX_VALUE))
         .addComponent(txtTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(5, 5, 5)
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btnSalvar)
               .addComponent(jButton1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
      try {
         opInsere.clearParameters();
         opInsere.setString(1, txtNome.getText());
         opInsere.setString(2, txtTelefone.getText());
         opInsere.executeUpdate();
         txtNome.setText("");
         txtTelefone.setText("");
         tblPessoa.updateUI();
         txtNome.requestFocus();
      } catch (SQLException ex) {
         JOptionPane.showMessageDialog(this, "Erro salvar os dados", "Erro na inserção!", JOptionPane.ERROR_MESSAGE);
         Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
      }

   }//GEN-LAST:event_btnSalvarActionPerformed

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try {
         if(tblPessoa.getSelectedRowCount()==0) return;
         Integer linha = tblPessoa.getSelectedRow();
         String telefone = (String) tblPessoa.getValueAt(linha, 1);
         opExclui.clearParameters();
         opExclui.setString(1, telefone);
         opExclui.executeUpdate();
         tblPessoa.clearSelection();
         tblPessoa.updateUI();
      } catch (SQLException ex) {
         JOptionPane.showMessageDialog(this, "Não foi possível excluir o registro!", "Erro ao excluir!", JOptionPane.ERROR_MESSAGE);
         Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
      }
   }//GEN-LAST:event_jButton1ActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new JanelaPrincipal().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnSalvar;
   private javax.swing.JButton jButton1;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTable tblPessoa;
   private javax.swing.JTextField txtNome;
   private javax.swing.JTextField txtTelefone;
   // End of variables declaration//GEN-END:variables
}
